### ISSUE TITLE
Adding "Our Team" Section using Tailwind CSS

### ISSUE THREAD

**Issue by abhishekjani08** [dear-digital/shopify-theme-skeleton#100]
**Is your feature request related to a problem? Please describe.**
Currently, our Shopify theme lacks a dedicated section that showcases the team members. Having such a section is vital for building trust with our customers by highlighting the people behind our brand.

**Describe the solution you'd like**
I propose the addition of an "Our Team" section within the theme. This section should be easily customizable through the theme editor, allowing for the addition of team member photos, names, titles, and brief descriptions. The design should be clean and professional, aligning with our brand aesthetics.

**Screenshots:**
Design would look like:
![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/88500027/863b0feb-4008-4924-bf2c-0e5628dfc285)
The design would be a responsive design and each team member's profile will include icons linked to their respective social media profiles, allowing for easy connection and fostering a community around our brand. This enhancement will align with our commitment to transparency and building a personal connection with our audience.

I will also change the schemas and give a add background color option to the user for their convenience and for a good user experience.

**Comment by mihir-bombay-studio** [comment]
You can create a generic section called dev__card-(functionality).liquid instead that can be customised to looklike team section as well

**Comment by abhishekjani08** [comment]
> > You can create a generic section called dev__card-(functionality).liquid instead that can be customised to looklike team section as well
> 
> @mihir-bombay-studio so i should create a file named as dev__card-(functionality).liquid which looks the image given above using tailwind css, the default things will look like "Our Team" Section but the user can change it as per his/her needs. Am i correct?

@mihir-bombay-studio Sir, can you please help me with this doubt?

**Comment by mihir-bombay-studio** [comment]
Yes that's correct @abhishekjani08 , you can create a new card section but make sure that the design you want to create isn't possible to do with the existing sections such as this [card section](https://github.com/dear-digital/shopify-theme-skeleton/blob/main/sections/dev__cards.liquid).
