### ISSUE TITLE
💡 [FEATURE]: Redesign the header section to incorporate dynamic styling capabilities

### ISSUE THREAD

**Issue by kmalap05** [dear-digital/shopify-theme-skeleton#134]
### Duplicate check

- [X] I have searched the existing issues

### Feature Description

I've identified a limitation in the current state of the project regarding the customization of HTML elements/tags. Presently, users face constraints in dynamically styling these elements, causing inconvenience.

### Motivation

**User-Friendly Styling:**
- By integrating Tailwind CSS classes as presets, we empower end-users to make stylistic changes effortlessly through the theme editor. This reduces the barrier to entry for users with limited coding experience.

**Consistency Across Sections:**
- Tailwind CSS classes provide a consistent styling framework across different sections, promoting a unified and professional appearance for the entire website.

### Additional Context

**Theme Editor Convenience:**
- Users can now have pre-defined styling options directly from the theme editor, eliminating the need for extensive manual customization.

**Flexibility for Advanced Users:**
- While Tailwind CSS classes provide simplicity for beginners, advanced users still have the flexibility to further customize styles by modifying the provided classes.

### File Modifications

- Delete: assets/dev__header.css
- Update: sections/dev__header.liquid

### Information Completeness

- [X] Yes, I have provided all the necessary information

**Comment by mihir-bombay-studio** [comment]
@kmalap05 Lets keep the issues more concise so it's easier to read

**Comment by kmalap05** [comment]
I'll attempt to finish this issue over the weekend.
