### ISSUE TITLE
🐞 [BUG] Unwanted File in Sections Folder

### ISSUE THREAD

**Issue by abhishekjani08** [dear-digital/shopify-theme-skeleton#145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The header-group.json file is a unwanted file or a file which is not making any change in our shopify theme.
This file is present in our sections folder and i think it should be removed as it makes of no use.
Also it shows an error that:  Section type 'header' does not refer to an existing section file.

### Steps To Reproduce

1. Go to sections folder
2. You can see header-group.json
3. Terminal shows error of :  Section type 'header' does not refer to an existing section file

### Screenshots

![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/88500027/afec5fd7-a418-4788-8990-a0d772008897)

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### OS

Windows

### Have you provided all details?

- [X] Yes, I have provided as much detail as possible

### Solution Hint

Remove the file

### File Modifications

Delete: header-group.json

**Comment by abhishekjani08** [comment]
Yes, i understood the issue.
🚀I surely want to work on this issue and will try to fix this bug.

**Comment by mihir-bombay-studio** [comment]
@abhishekjani08 Yes it is correct! 🙌

**Comment by mihir-bombay-studio** [comment]
@abhishekjani08  congratulations for reaching this first milestone 🎉 .
You can send your invoice to [mihir@deardigital.com](mailto:mihir@deardigital.com)
make the invoice of 10,000INR
Format will be the same as before. You can ask me on discord if you have any doubts regarding this.

Keep up the good work!!

**Comment by abhishekjani08** [comment]
> @abhishekjani08 congratulations for reaching this first milestone 🎉 . You can send your invoice to [mihir@deardigital.com](mailto:mihir@deardigital.com) make the invoice of 10,000INR Format will be the same as before. You can ask me on discord if you have any doubts regarding this.
> 
> Keep up the good work!!

Sure sir and thankyou for guiding us all the time!🚀
