### ISSUE TITLE
💡 [FEATURE]: Creating a PR Template

### ISSUE THREAD

**Issue by abhishekjani08** [dear-digital/shopify-theme-skeleton#146]
### Duplicate check

- [X] I have searched the existing issues

### Feature Description

I am going to create a PR Template for this repository.

Sections added into the template would be :

1. Fixing Issue Number
2. Type of Pull Request (Bug, Feature or Enhancements to code style (e.g., formatting, local variables)
3. PR Description/ Summary
4. What approach did you take?
5. Demo links/ Screenshots
6. A checklist of various things like :  
            Added PR summary
            Followed theme code principles
            Checked for any warnings by shopify theme check
            Linted with Theme Check
            Tested for Responsive
            Tested on multiple browsers
            Tested for accessibility
7. Lastly a conclusion/declaration by the collaborator that the details provided in this PR are correct to his/her knowledge.

### Motivation

Pull Request (PR) templates play a crucial role in software development by establishing a standardized format for submitting and reviewing code changes. They ensure consistency in the information provided by contributors.

### File Modifications

Create: PULL_REQUEST_TEMPLATE.md under the .github folder

### Information Completeness

- [X] Yes, I have provided all the necessary information

**Comment by mihir-bombay-studio** [comment]
@abhishekjani08 Let's keep the PR template as simple as possible.
