### ISSUE TITLE
💡 [FEATURE]: Reduce Custom CSS of Animation in Notification Section

### ISSUE THREAD

**Issue by anishdalvi** [dear-digital/shopify-theme-skeleton#155]
### Duplicate check

- [X] I have searched the existing issues

### Feature Description

![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/70633140/5a86bd4e-dd05-41f2-bfc2-fdb20527f644)

The blinking circle animation is currently hardcoded which disables user from editing its speed(if needed). We can add the blinking circle animation CSS in Tailwind Format via the class which can be editable from theme editor. Thus, user can control the speed of the blinking circle. This increases the customization option for the users.

### Motivation

The motivation behind this improvement is rooted in our overarching goal to minimize the usage of custom CSS in favor of Tailwind CSS. 

### File Modifications

Update: `dev__notification-bar.liquid`

### Information Completeness

- [X] Yes, I have provided all the necessary information

**Comment by mihir-bombay-studio** [comment]
@anishdalvi  congratulations for reaching this milestone 🎉 .
You can send your invoice to [mihir@deardigital.com](mailto:mihir@deardigital.com)
make the invoice of 10,000INR
Format will be the same as before. You can ask me on discord if you have any doubts regarding this.

Keep up the good work!!
