### ISSUE TITLE
💡 [FEATURE]: Adding "Icon Bar" Section into our theme

### ISSUE THREAD

**Issue by tanujbordikar** [dear-digital/shopify-theme-skeleton#165]
### Duplicate check

- [X] I have searched the existing issues

### Feature Description

Integrate schema support for the "icon-bar" section in the theme editor, allowing users to specify the name of the icon they want to display. The integration should utilize the 'icons.liquid' file in the snippet folder and enable users to customize icons seamlessly.

### Motivation

Currently, there is no "icon-bar" section which lacks direct theme editor support for selecting icons. By implementing schema integration and providing a field to input the icon name, users can easily customize their icon bars without needing to dive into code. This enhancement simplifies the customization process and empowers users to personalize their themes more efficiently.
![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/91179998/bbc64297-d13b-46c7-a263-b5b9be6dfb0c)

### Additional Context

To achieve this feature, the following Liquid code snippet can be used as an example:
```
{% if block.settings.icon != blank %}
     {% include 'icons', name: block.settings.icon | downcase, size: section.settings.size %}
{% endif %}
```
This code checks if an icon name is provided in the theme editor settings for the "icon-bar" section. If a name is present, it includes the 'icons' snippet with the specified icon name and size.

### File Modifications

Add `dev__icon-bar.liquid` file.

### Information Completeness

- [X] Yes, I have provided all the necessary information

**Comment by mihir-bombay-studio** [comment]
@tanujbordikar I don't think we can create a section out of this. Section should be as multipurpose as it can be for example a section for multicolumn can be customized to have icons as columns

**Comment by tanujbordikar** [comment]
> @tanujbordikar I don't think we can create a section out of this. Section should be as multipurpose as it can be for example a section for multicolumn can be customized to have icons as columns

Sir, If I apply this feature into the footer section is it okay??
