### ISSUE TITLE
💡 [FEATURE]: Updating image_url filter in multiple files

### ISSUE THREAD

**Issue by tanujbordikar** [dear-digital/shopify-theme-skeleton#179]
### Duplicate check

- [X] I have searched the existing issues

### Feature Description

1. The current issue pertains to the image_url filter, which currently lacks the utilization of the class attribute. As a result, styling for images is embedded within style tags. The proposed feature involves enhancing the image_url filter by incorporating the class attribute. This modification will enable the removal of custom CSS declarations within style tags, aligning with our transition towards a Tailwind CSS approach.
![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/91179998/e92fb542-bc5c-4874-be59-26e67c87f9f9)

2. Also changing it in `dev__featured_blogs.liquid` file.
![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/91179998/17f4be8c-513e-4f49-b586-a2611021856b)

3. In `dev__multi-column.liquid` file
![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/91179998/dbcf8ab1-a576-4a27-b071-b346820be42a)

### Motivation

This improvement is driven by our overarching objective to reduce reliance on custom CSS and embrace Tailwind CSS. Introducing the class attribute to the image_url filter allows us to effortlessly incorporate Tailwind classes for styling, promoting a more streamlined and standardized approach to image styling throughout our theme.

### File Modifications

Updating `dev__logo-carousal.liquid`,  `dev__multi-column.liquid` and `dev__featured_blogs.liquid` file.

### Information Completeness

- [X] Yes, I have provided all the necessary information

**Comment by mihir-bombay-studio** [comment]
@tanujbordikar This section already has classes schema added to the images. Can you explain further what exact changes you would like to make?

**Comment by tanujbordikar** [comment]
For Example:
```
{% assign image-url_width = section.settings.image_width %}
{% assign image-url_height = section.settings.image_height %}
{% assign testimonial_image_classes = "testimonial__image " | append: testimonial.settings.image_styles %}
{{
 testimonial.settings.testimonial_image
                | image_url: width: image-url_width, height: image-url_height
                | image_tag: class: testimonial_image_classes, alt: testimonial.settings.image_name
}}
```

**Comment by tanujbordikar** [comment]
Hey @mihir-bombay-studio sir, I have broaden the scope of this issue to some more files.

**Comment by mihir-bombay-studio** [comment]
@tanujbordikar update only those files that need improvement.

**Comment by mihir-bombay-studio** [comment]
@tanujbordikar congratulations for reaching this milestone 🎉 .
You can send your invoice to [mihir@deardigital.com](mailto:mihir@deardigital.com)
make the invoice of 10,000INR
You can ask me on discord if you have any doubts regarding this.

Focus on quality of PR that you submit rather than quantity. In the begining as you learn new technologies start of slow keep focus on gaining knowledge and doing small tasks in the best possible way. Use AI chat models extensively, Check learning resources, see what others are doing, do your own research and eventually you'll gain enough experience to make quality PRs consistently and quickly.

**Comment by tanujbordikar** [comment]
> @tanujbordikar congratulations for reaching this milestone 🎉 . You can send your invoice to [mihir@deardigital.com](mailto:mihir@deardigital.com) make the invoice of 10,000INR You can ask me on discord if you have any doubts regarding this.
> 
> Focus on quality of PR that you submit rather than quantity. In the begining as you learn new technologies start of slow keep focus on gaining knowledge and doing small tasks in the best possible way. Use AI chat models extensively, Check learning resources, see what others are doing, do your own research and eventually you'll gain enough experience to make quality PRs consistently and quickly.

Thank you @mihir-bombay-studio Sir for your guidance and support throughout this journey. I'll make sure that I focus on how to improve the quality of PR's and be a avid learner.
