### ISSUE TITLE
💡 [FEATURE]: Introducing Footer Section using footer-group.json

### ISSUE THREAD

**Issue by abhishekjani08** [dear-digital/shopify-theme-skeleton#180]
### Duplicate check

- [X] I have searched the existing issues

### Feature Description

Introduce a Footer Section using footer-group.json, inspired by the functionality present in the Dawn theme. The Footer Section should allow users to easily customize and display footer content within the theme.

### Motivation

The addition of a Footer Section is crucial for several reasons:

Consistency with Best Practices:
Many modern themes, including Dawn, incorporate a Footer Section to maintain a consistent and organized layout. Implementing this feature aligns our theme with industry best practices.

Enhanced User Customization:
Users often seek customization options for the footer of their websites. This feature provides an easy-to-use solution for users to personalize their site's footer content.

### Additional Context

We dont have any footer section:
![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/88500027/a9f7deef-9cb6-4880-a49c-016fd3b4b930)

It looks like this(Dawn theme has this footer section):
![Screenshot 2023-12-07 151937](https://github.com/dear-digital/shopify-theme-skeleton/assets/88500027/b4a24d6c-1a28-4a7e-a452-106221fc9e4c)

### File Modifications

Create: footer-group.json
Update: theme.liquid (for adding footer section)

### Information Completeness

- [X] Yes, I have provided all the necessary information

**Comment by mihir-bombay-studio** [comment]
Related to issue #145

**Comment by abhishekjani08** [comment]
Sir, in issue No #145 we had just added the header-group.json.
This issue ticket was raised to add the footer-group.json which was not integrated till now!
What can we do now?
