### ISSUE TITLE
💡 [FEATURE]: Adding Back to Top Button in `theme.liquid` using Snippets

### ISSUE THREAD

**Issue by tanujbordikar** [dear-digital/shopify-theme-skeleton#183]
### Duplicate check

- [X] I have searched the existing issues

### Feature Description

Implement a "Back to Top" button in the theme.liquid file using snippets. This feature will enhance user experience by allowing them to easily navigate back to the top of the page with a single click.
*Similar to this:*
![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/91179998/63df2878-2c69-45d1-9ff8-237697535881)

### Motivation

A "Back to Top" button is a common and user-friendly feature that improves website usability. It provides a convenient way for users to quickly scroll back to the top of a page, especially in cases where the content is lengthy. This addition aligns with best practices for enhancing the overall user experience of the theme.

### Additional Context

"Back to Top" button: [Adding Back to Top Button in Vintage Themes](https://help.shopify.com/en/manual/online-store/themes/themes-by-shopify/vintage-themes/customizing-vintage-themes/add-back-to-top).

### File Modifications

Adding `back-to-the-top.liquid` file in `snippets` folder

### Information Completeness

- [X] Yes, I have provided all the necessary information

**Comment by mihir-bombay-studio** [comment]
@tanujbordikar you can create a section for it instead of snippet and we can add it from the `{% sections 'overlay' %}` section group later when we implemet it.

**Comment by tanujbordikar** [comment]
> @tanujbordikar you can create a section for it instead of snippet and we can add it from the `{% sections 'overlay' %}` section group later when we implemet it.

Got it, Sir.
