### ISSUE TITLE
💡 [FEATURE]: Revamping Google Map Section

### ISSUE THREAD

**Issue by tanujbordikar** [dear-digital/shopify-theme-skeleton#184]
### Duplicate check

- [X] I have searched the existing issues

### Feature Description

- Revamp the existing Google Map section in Shopify using Tailwind CSS for improved styling, responsiveness, and a modern look. Tailwind CSS will be utilized to enhance the visual aspects of the map section, providing a seamless and aesthetically pleasing user experience.
- Integrating with a small container specifying Address, Email and Phone number of particular address!

*Similar to :*
![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/91179998/1e48012c-aed6-423e-9a7c-f4a7f73f12f4)
![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/91179998/8e45b9ed-802c-42c9-9d98-3358e3694755)

### Motivation

This Google Map section can benefit from a design overhaul to align with modern web design trends and provide a more visually appealing experience for users. Tailwind CSS, with its utility-first approach, will streamline the styling process and allow for easy customization.

### Additional Context

Tailwind CSS components: [Tailblocks](https://tailblocks.cc/).
[link](https://www.maps.ie/create-google-map/)

### File Modifications

Updating `dev__map.liquid` file

### Information Completeness

- [X] Yes, I have provided all the necessary information

**Comment by mihir-bombay-studio** [comment]
Bumping points from 2 -> 3 for an excellent addition to the map section
