### ISSUE TITLE
💡 [FEATURE]: Code Optimization

### ISSUE THREAD

**Issue by kmalap05** [dear-digital/shopify-theme-skeleton#187]
### Duplicate check

- [X] I have searched the existing issues

### **1. Alt Text & Lazy Loading for image:**
Add alt text to the product images for accessibility. This is important for users who rely on screen readers.
```
{{ block.settings.image | image_url: width: '300px', height: '300px', alt: block.settings.title, loading: 'lazy' }}
```

### **2. Conditional Tags Rendering**
Wrap the script tags in a conditional check to ensure they are only rendered if there are tabs present. This can help prevent potential issues if the script runs on a page where this code isn't used.
```
{% if section.blocks.size > 1 %}
<script>
  // Your script here
</script>
{% endif %}
```

### **3. Avoiding Console Logs:**
Remove all console.log present in the `dev__featured-collection.liquid` file.

### **4. Async Script Loading:**
Consider using the async attribute when loading external scripts to prevent blocking the rendering of your page.
```
<script async></script>
```

### **5. Avoiding Unused Variables:**
If not using the formattedTag variable elsewhere, we can directly use the tag variable in the loop.

Previous Code:
```
{% for tag in tags %}
    {% assign formattedTag = tag | replace: '_', ' ' | capitalize %}
        <a
            href="#"
            class="featured-collection__tab-link"
            data-category="{{ formattedTag | handle }}">
            {{- formattedTag -}}
        </a>
{% endfor %}
```

After Updating:
```
<a href="#" class="featured-collection__tab-link" data-category="{{ tag | replace: '_', ' ' | capitalize | handle }}">
   {{- tag | replace: '_', ' ' | capitalize -}}
</a>
```

### **6. Cache Repeated DOM Queries:**
If working with a large number of elements, consider caching repeated DOM queries outside of the loop to improve performance.

Current Code:
```
<script>
  document.addEventListener('DOMContentLoaded', function () {
    const tabs = document.querySelectorAll('.featured-collection__tab-link');
    console.log('Tabs found:', tabs.length);
    const debounceFilter = _.debounce(filterProducts, 300);
  
  
    tabs.forEach((tab) => {
      tab.addEventListener('click', function (e) {
        e.preventDefault();
        console.log('Tab clicked:', this.innerText);
  
        tabs.forEach((t) => t.classList.remove('active'));
        this.classList.add('active');
  
        const category = this.getAttribute('data-category');
        console.log('Filtering category:', category);
        filterProducts(category);
      });
    });
  
    function filterProducts(category) {
      const allProductCards = document.querySelectorAll('.featured-collection__product-card');
      allProductCards.forEach((card) => {
        const isActive = category === 'all';
        card.style.display = isActive || category === card.dataset.category ? 'inline-block' : 'none';
      });
    }
  
    filterProducts('all');
  });
</script>
```

After Updating:
```
<script>
  document.addEventListener('DOMContentLoaded', function () {
    const tabs = document.querySelectorAll('.featured-collection__tab-link');
    const productCards = document.querySelectorAll('.featured-collection__product-card');

    tabs.forEach((tab) => {
      tab.addEventListener('click', function (e) {
        e.preventDefault();

        tabs.forEach((t) => t.classList.remove('active'));
        this.classList.add('active');

        const category = this.getAttribute('data-category');
        filterProducts(category);
      });
    });

    function filterProducts(category) {
      productCards.forEach((card) => {
        const isActive = category === 'all';
        card.style.display = isActive || category === card.dataset.category ? 'inline-block' : 'none';
      });
    }

    filterProducts('all');
  });
</script>
```

### Motivation

- These optimizations improve accessibility and performance by adding alt text, lazy loading images, and using async script loading. 
- Conditional rendering enhances modularity, while removing console logs ensures cleaner code. 
- Eliminating unused variables and caching DOM queries streamline efficiency, aligning with best practices for maintainability. 

### Additional Context

- Ensure compatibility, no breaking changes. Emphasize performance gains for pages with many elements or diverse accessibility needs. 
- Highlight alignment with coding best practices for maintainability and long-term sustainability. 
- Feedback welcome for refinement.

### File Modifications

Update: dev__featured-collection.liquid

### Information Completeness

- [X] Yes, I have provided all the necessary information

**Comment by mihir-bombay-studio** [comment]
@kmalap05 Make sure that all changes that you make only progressively enhances the theme. for the image tag shopify itself has a lot of support for lazy loading and alt tag in liquid you can check out the documentantation and this [blog](https://performance.shopify.com/blogs/blog/announcing-new-liquid-features-for-better-web-performance)
