### ISSUE TITLE
🐞 [BUG] Removing Local shopify theme check Errors

### ISSUE THREAD

**Issue by tanujbordikar** [dear-digital/shopify-theme-skeleton#188]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The local Shopify theme check throws errors in the schemas of `dev__video-text.liquid` files due to addition of tailwind schemas. The issue is specifically related to the need for improving JSON formatting in the schema section.

### Steps To Reproduce

1. Go to terminal
2. Write the command for checking i.e. shopify theme check

### Screenshots

![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/91179998/fb4dae31-7c52-459d-a5de-7bd8afdfca3b)

### What browsers are you seeing the problem on?

Chrome

### OS

Windows

### Have you provided all details?

- [X] Yes, I have provided as much detail as possible

### Solution Hint

Reviewing and updation of the code in `dev__video-text.liquid` to address the enhanced JSON formatting. This will ensure compliance with the latest standards and resolve the issues raised by the `shopify theme check`.

### File Modifications

Update `dev__video-text.liquid`

**Comment by mihir-bombay-studio** [comment]
@tanujbordikar Are you sure about this? I don't see any errors in this section in theme check on the main branch

**Comment by tanujbordikar** [comment]
> @tanujbordikar Are you sure about this? I don't see any errors in this section in theme check on the main branch
I think it is related to annotations!
![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/91179998/68124565-0f49-40bf-a37d-de65f915550e)
