### ISSUE TITLE
💡 [FEATURE]: Add Slideshow Feature

### ISSUE THREAD

**Issue by kmalap05** [dear-digital/shopify-theme-skeleton#189]
### Duplicate check

- [X] I have searched the existing issues

### Related Issues

Issue No: #105 

### Feature Description

https://github.com/dear-digital/shopify-theme-skeleton/assets/83391228/d0214e62-6a9b-4a95-bd91-11e9eb340ae7

### Motivation

Addressing the previously mentioned concern for enhancement.

### File Modifications

Create: dev__slideshow.liquid

### Information Completeness

- [X] Yes, I have provided all the necessary information

**Comment by mihir-bombay-studio** [comment]
Thanks for creating a feature request for slideshow but lets wait until we collectively decide which javascript methodology and libraries we should use before implementing sections that require extensive javascript.
