### ISSUE TITLE
Flexbox Feature Implementation for new "dev__flex-box.liquid" Section

### ISSUE THREAD

**Issue by mihir-bombay-studio** [dear-digital/shopify-theme-skeleton#19]
We need to add/enhance the `dev__flex-box` section with advanced flexbox capabilities, allowing users to manipulate layout properties akin to sophisticated web builders like Webflow. This feature should offer intuitive UI controls for flexbox properties such as display, direction, alignment, justification, gap, and children wrapping, as exemplified in the provided UI mockup.

**Acceptance Criteria:**
1. Direction toggles for flex-direction: row (horizontal), column (vertical).
2. Alignment tools for align-items: stretch, center, flex-start, flex-end(check image/webflow link).
3. Justification tools for justify-content: space-between, space-around, center, flex-start, flex-end(check image/webflow link).
4. Input fields for gap spacing between flex items and rows.
5. Toggles for flex-wrap: nowrap, wrap.

**Required Changes:**
- Clone the existing `dev__multi-purpose` section as a starting point.
- Introduce additional Liquid variables and corresponding schema settings for the new flexbox properties.
- Update the section's HTML and/or CSS to reflect changes dynamically based on the user's selections in the theme editor.
- Ensure all new code is clean, maintainable, and efficient.

**Notes:**
- Explore Webflow's theme editor, specifically the flexbox section at [Webflow Example Link](https://preview.webflow.com/preview/sdfgsdfgs-blank-site-22bb6c?utm_medium=preview_link&utm_source=designer&utm_content=sdfgsdfgs-blank-site-22bb6c&preview=17eb1cf65f40fa381c01538491798184) to understand the user experience and feature set expectations.
- Implement headings in the theme editor UI to categorize flexbox customization settings for better usability like the headings for layour and spacing in [dev__multi-purpose](https://github.com/dear-digital/shopify-theme-skeleton/blob/develop/sections/dev__multi-purpose.liquid) section.

**Resources:**
- UI mockup image provided for the flexbox controls.
![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/78968174/a85e681f-fc56-4fd7-85d8-26b3be328885)

- Webflow's [editor link](https://preview.webflow.com/preview/sdfgsdfgs-blank-site-22bb6c?utm_medium=preview_link&utm_source=designer&utm_content=sdfgsdfgs-blank-site-22bb6c&preview=17eb1cf65f40fa381c01538491798184) for reference.
- Documentation and codebase of the [dev__multi-purpose](https://github.com/dear-digital/shopify-theme-skeleton/blob/develop/sections/dev__multi-purpose.liquid) section.

**Comment by kmalap05** [comment]
![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/83391228/565deda3-f8bf-4808-8e19-abf78818eb1e)

**Comment by kmalap05** [comment]
**Is this the correct way to implement it?**

![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/83391228/8e31b247-ad5a-4908-84d0-6fffb3be08fc)

**Comment by abhishekjani08** [comment]
Even i researched on this topic:
So the shopify editor doesnot helps us to hide the items(when selected display mode to flex then only show the advanced flex items) so i think its better to add a labelled text.

We can implement radio buttons like this:
![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/88500027/5f98cd73-d847-4c23-bf9c-2cfe621369e0)

Or else the select options with some labelled text:
![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/88500027/cdd13b41-91a8-446c-8f40-280c43fe203c)
 
To implement an advanced user interface for theme settings that utilizes select options accompanied by labeled text. This approach aims to improve user experience by providing clear, concise, and visually appealing configuration options within the Shopify theme editor.

From my perspective the adoption of select options with labeled text will provide a more formal and user-friendly interface within the Shopify theme editors.

**Comment by mihir-bombay-studio** [comment]
You guys are right currently we are limited with what we can do in shopify theme editor, so that's why we have to think about unique solutions at this point such as 
- give priority to settings that are most utilised in terms of placement
- use headings and info
and until shopify enhance their schema capabilities.

On the brighter side we know what we require now and hopefully shopify implements better tools in future and we can implement it asap.
