### ISSUE TITLE
💡 [FEATURE]:  Adding Footer Section

### ISSUE THREAD

**Issue by abhishekjani08** [dear-digital/shopify-theme-skeleton#190]
### Duplicate check

- [X] I have searched the existing issues

### Related Issues

My previous issue : #180 - Introducing Footer Section using footer-group.json #180

### Feature Description

As Discussed with Mihir Sir, I am reopening this issue request ticket and i am proposing to Introduce a Footer Section using footer-group.json, inspired by the functionality present in the Dawn theme. The Footer Section should allow users to easily customize and display footer content within the theme.

### Motivation

Many modern themes, including Dawn, incorporate a Footer Section to maintain a consistent and organized layout. Implementing this feature aligns our theme with industry best practices.
Also, Users often seek customization options for the footer of their websites. This feature provides an easy-to-use solution for users to personalize their site's footer content.

### Additional Context

It looks like this: 
![Screenshot 2023-12-07 151937](https://github.com/dear-digital/shopify-theme-skeleton/assets/88500027/b4a24d6c-1a28-4a7e-a452-106221fc9e4c)

### File Modifications

Create: footer-group.json
Update: theme.liquid (for adding footer section)

### Information Completeness

- [X] Yes, I have provided all the necessary information

**Comment by mihir-bombay-studio** [comment]
@abhishekjani08 can you also uncomment and implement the other section groups like overlay and drawers
