### ISSUE TITLE
🐞 [BUG] Improving Footer Section

### ISSUE THREAD

**Issue by tanujbordikar** [dear-digital/shopify-theme-skeleton#195]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

1. The footer section contains a heading element that is currently a radio button in the mobile-view and needs to be changed to a dropdown. 
2. Additionally the footer is not mobile-responsive.

### Steps To Reproduce

1. Open the website on a desktop browser.
2. Navigate to the footer section.
3. Observe the heading element being a radio button.

### Screenshots

Current Issue:
![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/91179998/651eb949-1065-436e-a5c7-c86bab4e80b8)

After Changes:
![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/91179998/3cc92607-73b3-4dfb-a491-028a40f20421)

### What browsers are you seeing the problem on?

Chrome

### OS

Windows

### Have you provided all details?

- [X] Yes, I have provided as much detail as possible

### Solution Hint

1. **Changing Heading Element to Dropdown:**
   - Identifying the HTML and CSS code responsible for rendering the footer heading element.
   - Replacing the radio button with a dropdown element (e.g., `<select>` and `<option>`).

```html
<!-- Before -->
<input type="checkbox" id="footer-toggle-{{ forloop.index }}" 
            class="footer__toggle-checkbox {{ block.settings.footer__toggle-checkbox }}">
<!-- After -->
<select name="footer-heading">
  <option value="Option1">Option 1</option>
  <!-- Add more options as needed -->
</select>
```

2. **Mobile Responsiveness:**
   - Use media queries in the CSS to define styles specifically for mobile devices.
   - Ensure that the layout and styling adapt appropriately for smaller screens.

### File Modifications

`dev__footer.liquid`

**Comment by mihir-bombay-studio** [comment]
@tanujbordikar select option is not the best for displaying custom designed elements as the design for select is predefined at browser level

**Comment by tanujbordikar** [comment]
> @tanujbordikar select option is not the best for displaying custom designed elements as the design for select is predefined at browser level

So @mihir-bombay-studio sir it is okay that I'll find some another solution to tackle this bug??
