### ISSUE TITLE
🐞 [BUG] Updating Image Banner Display Section

### ISSUE THREAD

**Issue by abhishekjani08** [dear-digital/shopify-theme-skeleton#203]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The image of Image Banner starts getting compressed as we start adding a description to it.
Also we have change the schema of Description to textarea from text.

### Screenshots

Whenever we add any big paragraph as a description the image gets compressed.
![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/88500027/6d184c39-f700-488d-8e20-7be4fcb163fc)

### What browsers are you seeing the problem on?

Chrome

### OS

Windows

### Have you provided all details?

- [X] Yes, I have provided as much detail as possible

### Solution Hint

Change the CSS to fix the position of Image and text properly

### File Modifications

Update: dev__image-banner.liquid

**Comment by mihir-bombay-studio** [comment]
If this bug can be fixed by adding correct tailwind classes from the theme editor then we don't require to fix this bug
