### ISSUE TITLE
💡 [FEATURE]: Adding Sliding Feature for Announcement Bar

### ISSUE THREAD

**Issue by anishdalvi** [dear-digital/shopify-theme-skeleton#206]
### Duplicate check

- [X] I have searched the existing issues

### Feature Description

I propose adding a sliding feature to the announcement bar. This enhancement aims to enable smooth horizontal navigation within the announcement bar content. The sliding feature would allow users to easily view and interact with multiple announcements by navigating through them using intuitive controls.

### Motivation

The sliding feature is essential for enhancing user engagement and ensuring that multiple announcements are accessible within the limited space of the announcement bar. It provides a more dynamic and visually appealing way to present information, contributing to an improved user experience.

### Additional Context

The `global.js` file has AnnouncementSlider Class due to which there are errors in console.

![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/70633140/e1d8b8b8-6f38-4092-a8ee-215df9715340)

This feature should be carefully added & reviewed in order to remove such errors and keep the code clean as much as we can!

### File Modifications

Update: `dev__announcement-bar.liquid`

### Information Completeness

- [X] Yes, I have provided all the necessary information

**Comment by mihir-bombay-studio** [comment]
> This feature should be carefully added & reviewed in order to remove such errors and keep the code clean as much as we can!

Indeed, you can try to fix the errors and add some additional enhancement. But don't add a lot of modifications to javascript as we will decide the further js architecture and libraries to use.
