### ISSUE TITLE
🐞 [BUG] Blogs Not Visible After Addition

### ISSUE THREAD

**Issue by kmalap05** [dear-digital/shopify-theme-skeleton#208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

- After adding blogs, I've encountered an issue where they are not appearing as expected. 
- This visibility bug is hindering users from accessing newly added content. 
- The issue needs investigation to identify the root cause and implement a solution to ensure that all added blogs are visible to users.

### Steps To Reproduce

1. Navigate to the blog addition functionality in the codebase (sections.dev__featured-blogs.liquid).
2. Add a new blog using the standard procedure.
3. Save the changes and attempt to view the newly added blog on the user interface.

### Screenshots

![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/83391228/1eef7e06-c88f-433e-a20e-2294348e363a)

### What browsers are you seeing the problem on?

Chrome

### OS

Windows

### Have you provided all details?

- [X] Yes, I have provided as much detail as possible

### File Modifications

Update: sections/dev__featured-blogs.liquid

**Comment by anishdalvi** [comment]
For the blogs to be visible, you have to add Blog Posts in a particular blog with keeping Visibility as Visible.

Ref: 

![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/70633140/c7f59186-6af7-40bd-9595-9fe0d0a02ce3)

After adding blog posts to a Blog

here is the output: #166 

![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/70633140/a41f80df-c643-4210-acdc-31a2b43de83a)
