### ISSUE TITLE
💡 [FEATURE]: Enhance Contact Page Styling

### ISSUE THREAD

**Issue by kmalap05** [dear-digital/shopify-theme-skeleton#210]
### Duplicate check

- [X] I have searched the existing issues

### Feature Description

- This issue is raised to address the need for an improved styling on the contact page. 
- The current design lacks optimal aesthetics and user-friendly elements. 
- The objective is to enhance the visual appeal and usability of the contact page by focusing on styling updates. 

Current design:
![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/83391228/c68f2073-95c3-4260-a597-52b05b16f0fe)

Updating it to:
![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/83391228/31d50ee9-1289-47e2-99aa-cda18af5286a)

### Motivation

- Revamping the contact page styling aims to improve its visual appeal and user-friendliness. 
- An aesthetically pleasing and intuitive design enhances user engagement, making it easier for visitors to connect with us seamlessly. 
- This update aligns with our commitment to providing a positive and polished online experience.

### Additional Context

Reference: [Dawn Theme](https://github.com/Shopify/dawn/blob/main/sections/contact-form.liquid)

### File Modifications

Update: dev__contact-form.liquid

### Information Completeness

- [X] Yes, I have provided all the necessary information

**Comment by mihir-bombay-studio** [comment]
This issue seems to be primary targeted towards the styling of elements which we can achieve by using different tailwind classes from the theme editor. So let's keep design specific enhancement for later and focus on facilitating as much customizability in html as possible.
