### ISSUE TITLE
💡 [FEATURE]: Adding Drawer content using drawer-group.json 

### ISSUE THREAD

**Issue by abhishekjani08** [dear-digital/shopify-theme-skeleton#219]
### Duplicate check

- [X] I have searched the existing issues

### Feature Description

Introduce a Drawer Group Section using drawer-group.json. The Drawer Section should allow users to easily customize and display drawer-based content which will be added further.

### Motivation

This feature is important to enhance the user experience by allowing users to add and customize drawer content directly from the Drawer Group Section.

### Additional Context

In theme.liquid:
![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/88500027/34ace7b1-7254-4594-b662-c24d11375c2a)

### File Modifications

Create: drawer-group.json
Update: theme.liquid

### Information Completeness

- [X] Yes, I have provided all the necessary information

**Comment by mihir-bombay-studio** [comment]
Include this in issue #190
