### ISSUE TITLE
🐞 [BUG] Remove checkbox from footer!

### ISSUE THREAD

**Issue by tanujbordikar** [dear-digital/shopify-theme-skeleton#226]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Currently, the Shopify theme skeleton includes a checkbox in the footer section, which might not be necessary for all use cases. To enhance flexibility and cater to diverse design preferences, it would be beneficial to remove the checkbox from the footer.

### Steps To Reproduce

1. Navigate to the footer section of the Shopify theme skeleton.
2. Select Mobile View

### Screenshots

![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/91179998/79a7f795-d45f-42bd-94bb-b5c325459629)

### What browsers are you seeing the problem on?

Chrome

### OS

Windows

### Have you provided all details?

- [X] Yes, I have provided as much detail as possible

### File Modifications

Updating `dev__footer.liquid`

**Comment by mihir-bombay-studio** [comment]
We need the checkboxes to open or close the dropdowns
