### ISSUE TITLE
Add Featured Product Section to Shopify Theme

### ISSUE THREAD

**Issue by kmalap05** [dear-digital/shopify-theme-skeleton#260]
## **Objective:**
Implement a featured product section in the Shopify theme to highlight selected products on the homepage.

## **User Story:**
As a store owner, I want to showcase featured products prominently on the homepage to attract customer attention and promote sales.

## **Background/Context:**
A featured product section helps to promote specific products that are on sale, popular, or newly added to the store. This section typically appears on the homepage to grab the attention of visitors and encourage them to explore the featured products.

## **User Role:**
- [x] Store Owner/Administrator

## **Acceptance Criteria:**

- The featured product section should be customizable to display a selected number of products.
- Each featured product should include an image, title, price, add to cart button, full details link etc.
- Store owners should be able to easily manage and update the list of featured products.
- The featured product section should be responsive and visually appealing on desktop and mobile devices, including during zoom in and zoom out actions.

## **Technical Details (If Known):**

- The featured product section may require custom liquid code to fetch and display the featured products.
- CSS styling may be used to customize the appearance of the featured product section.

## **Reference Images:**
![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/83391228/11b5bf34-a52d-4d59-a99a-d603b66b97ba)

## **Estimated Effort:**
Medium

## **Issue Creator Details:**
**Developer Intern**
_Experience Level with Project: Intermediate_

**Comment by tanujbordikar** [comment]
Hey @kmalap05, In this issue the product details must be fetched from the Product added in the store?

**Comment by kmalap05** [comment]
Yes, fetching product details directly from the added products in the store would be more beneficial for this issue. It would ensure that the details are always up to date and reduce the risk of inconsistencies.

**Comment by kmalap05** [comment]
Yes @tanujbordikar, fetching product details directly from the added products in the store would be more beneficial for this issue. It would ensure that the details are always up to date and reduce the risk of inconsistencies.

**Comment by tanujbordikar** [comment]
> Yes @tanujbordikar, fetching product details directly from the added products in the store would be more beneficial for this issue. It would ensure that the details are always up to date and reduce the risk of inconsistencies.

Okayy got it then I'll try to attempt it!
