### ISSUE TITLE
Improve Design Consistency and Responsiveness for Cards Display and Cards - Team Display

### ISSUE THREAD

**Issue by kmalap05** [dear-digital/shopify-theme-skeleton#261]
## **Objective:**
Enhance the design consistency and responsiveness of the Shopify theme, particularly focusing on the cards display and cards - team display sections.

## **User Story:**
As a website visitor, I expect the design of the website to remain consistent and responsive regardless of the zoom level, ensuring a visually pleasing and user-friendly experience.

## **Background/Context:**
Currently, the design of the website's cards display and cards - team display sections becomes distorted when zooming in or out, leading to inconsistencies in the overall design and responsiveness. This issue needs to be addressed to maintain a professional and seamless browsing experience for visitors.

## **User Role:**
- [x] Visitor

## **Acceptance Criteria:**

- The design of the cards display and cards - team display sections should remain consistent and visually appealing when zooming in or out.
- The layout and alignment of elements within the sections should adjust dynamically to maintain responsiveness during zoom actions.
- Text, images, and other content within the sections should scale appropriately to ensure readability and aesthetic appeal at different zoom levels.

## **Technical Details (If Known):**

- CSS media queries and responsive design principles may be used to improve the responsiveness of the sections.
- Careful consideration of font sizes, spacing, and element proportions is necessary to maintain design consistency across different zoom levels.

## **Reference Images:**
As you can see when zooming in or out, the design of this section becomes distorted.
![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/83391228/32ab784f-a5d3-4d45-93a4-8e41b2b951ca)

## **Estimated Effort:**
 High

## **Issue Creator Details:**
**Developer Intern**
_Experience Level with Project: Intermediate_

**Comment by tanujbordikar** [comment]
@kmalap05 Wanted to ask, Is it like to create a new design which is going to be similar to theme and also ensuring its responsiveness too?

**Comment by kmalap05** [comment]
Yes, that's correct! The goal is to redesign it to provide an aesthetic look while ensuring that it remains highly responsive.
