### ISSUE TITLE
Implement Search Bar for Product Discovery 🔍 

### ISSUE THREAD

**Issue by anishdalvi** [dear-digital/shopify-theme-skeleton#262]
## Objective
- [x] New Feature

## User Story

As a customer, I want to have the ability to search for products directly from the top of the website, so that I can easily find the items I'm looking for without having to navigate through multiple pages.

## Background/Context

Our current theme lacks a search bar, requiring users to manually browse through product categories or collections to find items. By integrating a search bar into the theme's navigation, we can provide a more convenient and efficient way for customers to search for products.

The Search Bar icon is in navbar which is not functional yet.

![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/70633140/bdb14818-5fd5-4612-970c-9f5f1969531d)

You can view it after checking the Enable Search Icon from the Header Section of the Theme!

![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/70633140/1303cb5a-b504-4456-85a1-8e3d6791a68b)

![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/70633140/f0c9fec6-db0a-4739-8279-0b9ab9e32335)

## User Role
- [x] Customer

## Acceptance Criteria

1. The search bar should be prominently displayed at the top of the website, preferably within the navigation bar or header section.
2. Users should be able to enter search queries directly into the search bar.
3. Upon entering a search query and pressing "Enter" or clicking the search button, relevant product results should be displayed.
4. The search functionality should be intuitive and easy to use, with autocomplete suggestions if possible.
5. The search results page should present clear and relevant product listings based on the user's query.

## Technical Details (If Known)

- The search functionality may require backend integration to query the product database. 
- Client-side scripting may be used to handle user input and display search results dynamically.
- Customization of the search bar's appearance and behavior may require CSS styling and JavaScript.

## Estimated Effort
- [x] Medium

## Reference:

- [Dawn Theme Demo](https://themes.shopify.com/themes/dawn/styles/default/preview)

- [Dawn Theme Code](https://github.com/Shopify/dawn)

## Reference Images:

Search Bar:

![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/70633140/a3d9a356-e935-4172-b113-ab1ec7f84f1c)

Searching a Product:

![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/70633140/2cdfa761-e3a5-4210-9c9b-f2a5809cb603)

## Additional Notes/Considerations

- Since there is currently no search functionality in the theme, thorough testing will be required to ensure the search bar works as expected across different browsers and devices.
- Consider implementing features such as autocomplete suggestions to enhance the user experience and improve search accuracy.
- Ensure the search bar is responsive and seamlessly integrates with the theme's design without compromising usability.

## Issue Creator Details
**Web Developer**
_Experience Level with Project: Intermediate_

**Comment by tanujbordikar** [comment]
Hello @anishdalvi and @mihir-bombay-studio Sir, I've been working on implementing a search feature for products on my local system. Before proceeding further, I wanted to confirm if I'm on the right track. I've created a basic search functionality along with some CSS styling. If this approach seems acceptable, I'll try to attempt it by refining and completing the implementation. Let me know your thoughts and any feedback you may have. Thanks!


https://github.com/dear-digital/shopify-theme-skeleton/assets/91179998/14c3aeda-cba4-41ad-9370-25b634b6b5a5

**Comment by anishdalvi** [comment]
> Hello @anishdalvi and @mihir-bombay-studio Sir, I've been working on implementing a search feature for products on my local system. Before proceeding further, I wanted to confirm if I'm on the right track. I've created a basic search functionality along with some CSS styling. If this approach seems acceptable, I'll try to attempt it by refining and completing the implementation. Let me know your thoughts and any feedback you may have. Thanks!
> 
>  2024-03-29.18-14-14.mp4

Looks Good for now as the Search Bar functionality is working. Just remember to Remove unwanted things at the end since now I see there is an extra Hamburger Icon which might be not required later.

**Comment by tanujbordikar** [comment]
> > Hello @anishdalvi and @mihir-bombay-studio Sir, I've been working on implementing a search feature for products on my local system. Before proceeding further, I wanted to confirm if I'm on the right track. I've created a basic search functionality along with some CSS styling. If this approach seems acceptable, I'll try to attempt it by refining and completing the implementation. Let me know your thoughts and any feedback you may have. Thanks!
> > 2024-03-29.18-14-14.mp4
> 
> Looks Good for now as the Search Bar functionality is working. Just remember to Remove unwanted things at the end since now I see there is an extra Hamburger Icon which might be not required later.

Okay I'll remove that hamburger icon. And will try to improvise the styling part.

**Comment by tanujbordikar** [comment]
hey @mihir-bombay-studio, the work for this issue is almost done can you please assign me this issue!

**Comment by tanujbordikar** [comment]
hey @mihir-bombay-studio, the work for this issue is almost done can you please assign me this issue!
