### ISSUE TITLE
"Back to Top" Button Not Visible and Functional

### ISSUE THREAD

**Issue by kmalap05** [dear-digital/shopify-theme-skeleton#267]
## **Objective:**
To fix the visibility and functionality of the "Back to Top" button on the website.

## **User Story:**
As a user, I want to be able to easily return to the top of the page by clicking a "Back to Top" button, so that I can navigate the site more efficiently, especially on long pages.

## **Background/Context:**
The "Back to Top" button is intended to provide a convenient way for users to scroll back to the top of the webpage without manually scrolling. However, it has been reported that this button is currently neither visible to the users nor functional.

## **User Role:**
- [x] User

## **Acceptance Criteria:**

- The "Back to Top" button should be clearly visible on the screen when the user scrolls down beyond a certain point.
- Upon clicking the "Back to Top" button, the page should smoothly scroll to the top.
- The button should be accessible and functional across all pages of the website where applicable.
- The design and placement of the "Back to Top" button should be consistent with the website's overall design and usability principles.
- The button should be responsive and work properly on both desktop and mobile devices.

## **Technical Details (If Known):**
The issue may involve CSS for visibility and JavaScript for scroll functionality.
Review the current implementation to identify why the button is not appearing or functioning as expected.

## **Reference Images:**
![backtotopbtn](https://github.com/dear-digital/shopify-theme-skeleton/assets/83391228/401e2fa1-5f94-4668-ad70-8ed219c6a465)

## **Estimated Effort:**
Low to Medium

## **Issue Creator Details:**
**Developer Intern**
_Experience Level with Project: Intermediate_

**Comment by tanujbordikar** [comment]
I think adding content may solve it!
