### ISSUE TITLE
Implement Countdown Timer Functionality

### ISSUE THREAD

**Issue by abhishekjani08** [dear-digital/shopify-theme-skeleton#270]
## Objective
- [x] Feature request

## User Story
As a website visitor, I want to see a countdown timer that shows when a limited-time offer will expire. This will create a sense of urgency and encourage me to make a purchase before the offer ends.

## Background/Context
Countdown timers are a common marketing tactic used to create a sense of urgency and encourage customers to purchase items before a specific deadline. This can be effective in boosting sales and conversions.

## User Role
- [x] Visitor

## Acceptance Criteria

1. The countdown timer should be displayed prominently as a section where the limited-time offer is advertised.
2. The countdown timer should be clear and easy to read, and it should display the remaining time in days, hours, minutes, and seconds.
3. The countdown timer should be accurate and reflect the actual end time of the offer.
4. The design of the countdown timer should be consistent with the overall design of the Shopify theme.

## Technical Details (If Known)
There are two main approaches to implement the countdown timer(still not sure which can work):

- Using a JavaScript library: This is the recommended approach as it saves development time and offers more flexibility for customization. Many free libraries are available, such as Simple Countdown Timer (https://github.com/topics/countdown-timer) or Vanilla Countdown (https://gist.github.com/Log1x/c9bffcaf6db6836c217d9d19e4ed8d38).

- Building the countdown timer from scratch: While possible, this requires more development work and offers less flexibility for customization.

## Estimated Effort
- [x] Medium

## Some Reference Images
Design will look like:
![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/88500027/2194acd8-c4b1-46a3-bef0-4ffdc162539c)

## Issue Creator Details
_Developer Intern
Experience Level with Project: Intermediate_

**Comment by mihir-bombay-studio** [comment]
@abhishekjani08 nice feature idea, just a small correction in the issue, the user story should be from the pov of store manager and not the visitor.

**Comment by abhishekjani08** [comment]
Hello sir,
I just wanted to ask if the approach i am showing you in the video will work or not.
When i edit the date in the schemas, it is requiring one refresh or a save is working to reflect the change of date to appear in the countdown timer.

📽️Video demo:

https://github.com/dear-digital/shopify-theme-skeleton/assets/88500027/9abfa459-8040-4b6f-b5cc-ca036e5bd91d



🚀Also if there are any changes, please let me know i will work on it!
