### ISSUE TITLE
Fix Modal Window Overlay Section Functionality

### ISSUE THREAD

**Issue by kmalap05** [dear-digital/shopify-theme-skeleton#276]
## **Objective:**
To resolve the functionality issue with the modal window overlay section, specifically related to the close (X) button and the okay button.

## **User Story:**
As a user, I expect the close (X) button and the okay button in the modal window overlay section to work properly, so that I can interact with the modal and dismiss it when necessary.

## **Background/Context:**
The current implementation of the modal window overlay section lacks functionality, as clicking on the close (X) button or the okay button does not dismiss the modal as expected. This issue needs to be addressed to ensure a seamless user experience when interacting with modals on the website.

## **User Role:**
- [x] Website Visitor

## **Acceptance Criteria:**
1. Clicking on the close (X) button should dismiss the modal and return the user to the previous state of the webpage.
2. Clicking on the okay button should perform the intended action associated with the modal and then dismiss it.
3. The modal should behave consistently across different devices and browsers, ensuring that the close and okay buttons are functional.

## **Technical Details (If Known):**
- The issue may involve updating JavaScript code responsible for handling the modal functionality.
- CSS styles may need to be adjusted to ensure proper display and functionality of the modal and its buttons.

## **Reference Images:**
![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/83391228/9a18d99e-cdfb-4ad9-87f2-22112c7a3a80)

## **Estimated Effort:**
Low to Medium

## **Issue Creator Details:**
**Developer Intern**
_Experience Level with Project: Intermediate_

**Comment by abhishekjani08** [comment]
As shown in the video, is this output correct for this particular issue?
On adding a modal section to our theme, whenever we click the close icon or Okay button; the section doesnot gets hided/closed.
We just have to enable it from settings_schmas.json with some changes in the script of dev__modal.liquid, also the modal will always appear on first site load only.
Please refer to the video @mihir-bombay-studio sir and @kmalap05  , if the approach is correct then i will attempt this issue.


https://github.com/dear-digital/shopify-theme-skeleton/assets/88500027/0fc3bc1a-4135-461d-9c91-3ac8af2b09e6



Thankyou!

**Comment by kmalap05** [comment]
@abhishekjani08 Yes, it's a good approach.

**Comment by mihir-bombay-studio** [comment]
@abhishekjani08 Yes that is the correct approach
