### ISSUE TITLE
Create New Cart Page with Product Details

### ISSUE THREAD

**Issue by kmalap05** [dear-digital/shopify-theme-skeleton#277]
## **Objective:**
Implement a new cart page in the Shopify theme to display detailed information about the products added to the cart.

## **User Story:**
As a shopper, I want to view detailed information about the products in my cart, including product images, names, quantities, prices, and total cost, so that I can review my selections before proceeding to checkout.

## **Background/Context:**
The current cart page lacks detailed information about the products, which makes it difficult for shoppers to review their selections. By creating a new cart page with product details, we can enhance the shopping experience and reduce cart abandonment rates.

## **User Role:**
- [x] Shopper

## **Acceptance Criteria:**
1. The new cart page should display a list of products added to the cart, including product images, names, quantities, prices, and total cost for each item.
2. Shoppers should be able to update the quantity of each product or remove products from the cart directly on the cart page.
3. The cart page should display the subtotal, shipping costs (if applicable), and the total cost of the order.
4. Shoppers should have the option to continue shopping or proceed to checkout from the cart page.

## **Technical Details (If Known):**
- The cart page may require custom liquid code to fetch and display the product details.
- CSS styling may be used to format the cart page and improve its visual appeal.

## **Estimated Effort:**
Medium

## **Issue Creator Details:**
**Developer Intern**
_Experience Level with Project: Intermediate_

**Comment by mihir-bombay-studio** [comment]
Let's wait for the current cart issues to be resolved. After that you can reopen this issue if something can still be added.
