### ISSUE TITLE
Enhancing the scroll bar height of Featured Collection 

### ISSUE THREAD

**Issue by abhishekjani08** [dear-digital/shopify-theme-skeleton#286]
## Objective
- [x] Feature request

## User Story
As a website visitor, I faced a difficulty in scrolling the products in the featured collection section.

## User Role
- [x] Visitor

## Acceptance Criteria
1. Increase the height of the scroll bar.
2. Visitor will easily able to scroll now!

## Estimated Effort
- [x] Medium

## Reference Video 

https://github.com/dear-digital/shopify-theme-skeleton/assets/88500027/0c925f88-bbb6-45d0-88b7-03f91cb0e223

After changes:
![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/88500027/de77d97a-1c1d-4243-b59a-b66f0bc4a426)

## Issue Creator Details
_Developer Intern
Experience Level with Project: Intermediate_

**Comment by mihir-bombay-studio** [comment]
Instead you can make the scrollbar height adjustable from theme editor by adding a setting in schema as the scrollbar height would eventually depend on design and having flexibility to edit it would enhance the theme @abhishekjani08
