### ISSUE TITLE
Add global sections settings

### ISSUE THREAD

**Issue by Mri1662** [dear-digital/shopify-theme-skeleton#35]
**Is your feature request related to a problem? Please describe.**
I propose the addition of global section settings for borders and vertical spacing in order to enhance design consistency and efficiency across our platform. This feature would allow users to set standardized parameters for borders and vertical spacing throughout their projects, ensuring a cohesive and professional appearance.

**Describe the solution you'd like**
Border styles and corner radius have been tied to a section-wrapper classes, which have been added where needed to each applicable section. Some area that can receive borders are best left with some amount of padding and I've applied this via section-wrapper--padded. Additionally, some sections have full width display modes. Left and right borders and well as corner radius have been excluded in these cases.

Using this approach seemed like a good idea when there were more settings involved, but maybe now with just borders the styles can be applied directly to existing elements in each section.

Borders have been excluded from

- Featured collection
- Collection list
- Multicolumn

Vertical spacing is applied to global spaced-section type classes, but also to section specific stylesheets which override those global classes. I've also included the concept of “safe spacing” in some uses of these spacing variables to ensure some amount of spacing is used in sections where zero spacing isn't ideal. 

**Describe alternatives you've considered**

**Manual Section-by-Section Adjustment:**

- Users could continue adjusting borders and vertical spacing individually for each section. However, this approach is time-consuming and increases the likelihood of inconsistencies.

**Limited Theme Options:**

- Implementing a limited set of predefined themes with fixed borders and spacing could provide consistency but limits customization options and may not meet the diverse needs of our users.

**Partial Global Settings:**

- Implementing global settings for only a subset of design elements (e.g., color schemes) could be an alternative, but it might not address the comprehensive needs of users for borders and spacing.

**Additional context**
[dawn theme ](https://github.com/Shopify/dawn/blob/main/layout/theme.liquid)

**Comment by mihir-bombay-studio** [comment]
@Mri1662 can you add images or video to explain in short the issue? Just to make it easier to understand

**Comment by Mri1662** [comment]
![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/103936103/a73350f8-a51c-496d-aef2-0095a1c23775)
Add like this

**Comment by mihir-bombay-studio** [comment]
Is this feature present in dawn or other themes? can you link the dawn file url with it's line number?

**Comment by Mri1662** [comment]
<img width="668" alt="image" src="https://github.com/dear-digital/shopify-theme-skeleton/assets/103936103/0eaa7caa-0a6d-4bec-b92f-a6db4c390a22">
Yes feature present in dawn. You can see in this link [dawn theme.liquid](https://github.com/Shopify/dawn/blob/main/layout/theme.liquid)

**Comment by mihir-bombay-studio** [comment]
Great! Yes you can declare all settings coming from the theme editor settings like dawn does.
