### ISSUE TITLE
Navbar Implementation 

### ISSUE THREAD

**Issue by anishdalvi** [dear-digital/shopify-theme-skeleton#39]
### **Is your feature request related to a problem? Please describe.**
The current header.liquid file contains hardcoded navigation links, and it has been suggested to remove hardcoded text entirely for cleaner and more efficient code. To achieve a clean and customizable navbar, creating a new file specifically for the navbar is recommended.

Code :

<img src="https://github.com/dear-digital/shopify-theme-skeleton/assets/70633140/b17131fa-e69c-4ea7-83a0-ad834bef4328" height="500px" width="auto"/>

Output: 

![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/70633140/531ef6a7-a192-4921-a255-f66a30228c40)

### **Describe the solution you'd like**
Create a new file, possibly named `dev_navbar.liquid`, dedicated to the navigation bar. This file should include the necessary HTML and Liquid code for a clean navbar. Additionally, it should allow customization of navlinks via the theme editor, eliminating the need for hardcoded text in the header.liquid file.

### **Describe alternatives you've considered**
Alternative solutions include adding all navlinks directly to the header.liquid file. However, this approach may result in cluttered code and reduced efficiency, especially when dealing with multiple if tags. Creating a separate file for the navbar enhances code organization and maintainability.

### **Additional context**
Considering the advice given by you (Mihir Sir) to remove hardcoded text entirely and make everything customizable via the theme editor. This will contribute to a more streamlined and efficient Shopify theme.

**Comment by mihir-bombay-studio** [comment]
You can use [link-list](https://shopify.dev/docs/themes/architecture/settings/input-settings#link_list) input type to get menu items from shopify itself checkout this [usage example](https://github.com/Shopify/dawn/blob/b0ba46d4bb716f073e6ddbdc3560517c5c86c53e/sections/footer.liquid#L89)

**Comment by anishdalvi** [comment]
I've explored the provided links and looked into the menu implementation. I have a couple of questions to ensure a smooth implementation.

In most examples I've come across, the menu is implemented directly in the `header.liquid` file. Should I follow the same approach for consistency? Additionally, should I rename it as `dev_header.liquid` or keep it as `header.liquid`?

Also, regarding the CSS implementation, should I include the styles for this issue or not as the menu and sub-menu links will definitely differ in their CSS part.

As of now, I have successfully added the menu with sub-menus using [link-list](https://shopify.dev/docs/themes/architecture/settings/input-settings#link_list) 

Input Settings(Navbar Section):

![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/70633140/6daa96ce-445b-4d72-8e43-a2b4c7db0465)

Output:

![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/70633140/7015d2c1-88bd-4acb-8992-afa958c6d396)

**Comment by mihir-bombay-studio** [comment]
Let's keep the name `dev_header.liquid` as it is not fully ready for production. You can add css if you want to but make sure to name the css file `dev_header.css` use BEM and the css in that file should only be for elements in dev_header section

**Comment by anishdalvi** [comment]
> Let's keep the name `dev_header.liquid` as it is not fully ready for production. You can add css if you want to but make sure to name the css file `dev_header.css` use BEM and the css in that file should only be for elements in dev_header section

Okay.
