### ISSUE TITLE
Update header.liquid file Follow BEM Methodology 

### ISSUE THREAD

**Issue by Mri1662** [dear-digital/shopify-theme-skeleton#44]
**Is your feature request related to a problem? Please describe.**
The current implementation of header.liquid  section provided in the does not follow the BEM methodology, which can impact code maintainability and readability.

**Describe the solution you'd like**
I would like to propose updating the header in the Liquid section to adhere to the BEM methodology. 

**Describe alternatives you've considered**
An alternative would be to keep the existing class names without applying the BEM methodology. However, adopting BEM would enhance code organization and make it easier to understand the structure and relationships between different elements.

**Additional context**
It aligns with best practices in front-end development and improves the consistency and clarity of the class naming convention used throughout the project.

**Previous code (Without BEM):**
```
<header>
    <nav>
        <ul>
            <li><a href="/">Home</a></li>
            <li><a href="/about">About</a></li>
            <li><a href="/contact">Contact</a></li>
        </ul>
    </nav>
</header>
{{ section.settings.asdas }} 

{% schema %}
  {
  "name": "header",
  "class": "shopify-header",
  "settings": [
    {
      "type": "text",
      "id": "asdas",
      "label": "asdas"
    }
  ],
  "presets": [
    {
      "name": "header"
    }
  ]
}  
{% endschema %}

{% stylesheet %}
{% endstylesheet %}

{% javascript %}
{% endjavascript %}
```

**After Code (With BEM):**
```
<header class="header">
    <nav class="header__nav">
        <ul class="header__nav-list">
            <li class="header__nav-item"><a href="/" class="header__nav-link">Home</a></li>
            <li class="header__nav-item"><a href="/about" class="header__nav-link">About</a></li>
            <li class="header__nav-item"><a href="/contact" class="header__nav-link">Contact</a></li>
        </ul>
    </nav>
</header>
{{ section.settings.asdas }}

{% schema %}
{
  "name": "header",
  "class": "shopify-header",
  "settings": [
    {
      "type": "text",
      "id": "asdas",
      "label": "asdas"
    }
  ],
  "presets": [
    {
      "name": "header"
    }
  ]
}  
{% endschema %}

{% stylesheet %}
{% endstylesheet %}

{% javascript %}
{% endjavascript %}
```

**Comment by mihir-bombay-studio** [comment]
@Mri1662 we already have a [ticket](https://github.com/dear-digital/shopify-theme-skeleton/issues/39) for the header/navbar so let's wait for that to finish and if required afterwards we can repoen this ticket or create a new one regarding the same.
