### ISSUE TITLE
Add "Customer Showcase" Section for User-Generated Content

### ISSUE THREAD

**Issue by kmalap05** [dear-digital/shopify-theme-skeleton#49]
**Is your feature request related to a problem? Please describe.**
I believe that our current Shopify theme lacks a dedicated section to showcase customer photos using our products. This absence makes it challenging to build a sense of community and trust among potential customers.

**Describe the solution you'd like**
I propose the creation of a "Customer Showcase" section on the homepage where we can feature photos submitted by our customers, highlighting how they use our products. This section will not only serve as a visual testimonial but also foster a connection between our brand and our customers.

**Describe alternatives you've considered**
One alternative is leveraging social media platforms to share customer photos. However, having a dedicated section on our website provides a seamless and integrated experience for visitors. It allows us to curate and showcase a selection of customer photos directly on our site.

**Additional context**
- This feature aligns with the industry trend of user-generated content, enhancing our brand image.
- We could consider incorporating a submission form to encourage customers to share their photos.
- To maintain a consistent aesthetic, it's important to have guidelines for photo submissions (e.g., resolution, composition).

**Comment by mihir-bombay-studio** [comment]
Similar feature is being built in #48. After that is done you can create another ticket if you think more enhancement is required or something else needs to be added.
