### ISSUE TITLE
Schema Integration for [Section Name] = "featured-collection"

### ISSUE THREAD

**Issue by mihir-bombay-studio** [dear-digital/shopify-theme-skeleton#5]
Design can be found at website https://www.yummygums.com/.
Image of the section is pasted below.
![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/78968174/59e17884-85cb-476f-9022-38fdf4382427)

### Description
This issue involves integrating schema into the [Section Name] as per the design specifications of the Skeleton Shopify Theme. Add the file with the name `[section-name].liquid` to the `sections` folder if it does not exist already. This file will contain the schema for the [Section Name] section. The schema should be implemented according to the design specifications and allow for the necessary customization and input settings as identified in the design. The schema should also be tested and functional both on desktop and mobile views. Ensure that the code follows the project's coding standards and best practices. Any logical inconsistencies in the design should be addressed and standardized for end-user flexibility.

### Resources and Documentation
Before starting on this issue, please refer to our [Milestone 1: Schema Integration Documentation](https://github.com/dear-digital/shopify-theme-skeleton/blob/main/documentation/sections/README.md). This guide provides detailed steps and resources to assist you in this task.

### Acceptance Criteria
- [ ] The schema for [Section Name] is correctly implemented according to the design specifications.
- [ ] The schema allows for the necessary customization and input settings as identified in the design.
- [ ] Code follows the project's coding standards and best practices.
- [ ] Any logical inconsistencies in the design are addressed and standardized for end-user flexibility.

### How to Get Assigned
- If you're interested in working on this issue, comment `/attempt` below.
- You will be assigned based on your contribution level and previous work quality.
- Once assigned, you can start working on the issue and submit a pull request (PR) upon completion.

### Additional Notes
- Ensure to frequently communicate your progress and any challenges you face in this issue thread.
- If you have questions or need clarifications, feel free to ask in the comments or join our [Discord channel](https://discord.gg/axRUsACwPW) for a more in-depth discussion.

**Comment by anishdalvi** [comment]
Sir, the categories of the products should be static right? As the image has Four Categories Multivitamin, Wellness and Beauty, Single Support, Kids and All tabs? The issue concerns of adding products dynamically and display according to categories when clicked on Tabs correct?

**Comment by anishdalvi** [comment]
This is the Demo Video of the work which is almost done. [Link Here](https://drive.google.com/file/d/1L91j-QcANN0m2n4jg7HQKt0AebBLlIb3/view?usp=sharing)

The one thing which I am trying for **so long** is about the Tabs filtering after clicking on different tabs (categories). It mostly glitches and thus doesn't work everytime.

Video Working of Tabs filtering: [View](https://github.com/dear-digital/shopify-theme-skeleton/assets/70633140/96997ab1-b038-47a0-93f0-bb92915a6ed6)

(Featured Collection Branch) [Code](https://github.com/anishdalvi/shopify-theme-skeleton/tree/featured-collection)

These are some of the errors which were already prevailing and I think these are one of the reason for Glitch.

![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/70633140/12dd8c20-faaf-4e48-981a-5a62491f10ac)

Suggestions are Welcomed 🙌🏻

**Comment by mihir-bombay-studio** [comment]
Don't worry about the functioning of tabs for now. Just focus on the html so every element can be added via the theme editor. To add the tags you can either use blocks or use a text field with comma seperated tags and then using liquid filter split create an array of tags to loop over and display.
