### ISSUE TITLE
 Customizable Footer Section for the Shopify Skeleton Theme

### ISSUE THREAD

**Issue by abhishekjani08** [dear-digital/shopify-theme-skeleton#50]
**Is your feature request related to a problem? Please describe.**
The current Shopify Skeleton Theme lacks a robust and flexible footer section that can accommodate various content types, such as navigation links, contact information, newsletter sign-up forms, and social media icons. Users often struggle to customize the footer to match their brand's aesthetic and functional requirements.

**Describe the solution you'd like**
I would like a footer section implemented that is highly customizable with multiple columns for different content types. The footer should allow easy configuration of text, links, newsletter sign-up, and social media through the theme settings.

**Describe alternatives you've considered**
An alternative solution could be to use a pre-designed footer template. However, this might limit the customization options and not cater to specific business needs. Therefore, a built-in customizable option within the theme is preferred.

**Additional context**
The attached image shows a multi-column footer layout with distinct sections for company information, product range, vitamin info, and newsletter subscription. This layout should serve as a template for the customizable footer section in the theme.
Reference footer from : [Yummygums](https://www.yummygums.com/)

![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/88500027/a3dc49db-15a0-4f0e-a73d-caca2888e862)

**Comment by mihir-bombay-studio** [comment]
You can use [link-list](https://shopify.dev/docs/themes/architecture/settings/input-settings#link_list) input type to get menu items from shopify itself checkout this [usage example](https://github.com/Shopify/dawn/blob/b0ba46d4bb716f073e6ddbdc3560517c5c86c53e/sections/footer.liquid#L89)
