### ISSUE TITLE
Add Multi-Column Section 

### ISSUE THREAD

**Issue by anishdalvi** [dear-digital/shopify-theme-skeleton#60]
### **Is your feature request related to a problem? Please describe.**
The current absence of a multicolumn section in the Shopify skeleton theme limits the layout options available for organizing and presenting content. This can result in a less flexible and visually appealing design for certain types of information.

### **Describe the solution you'd like**
I suggest the inclusion of a multicolumn section in the Shopify skeleton theme, allowing merchants to easily create and customize multicolumn layouts. This feature would enhance the theme's versatility, providing a more dynamic and aesthetically pleasing structure for various types of content.

### **Describe alternatives you've considered**
Alternative solutions might involve using custom code to implement multicolumn layouts. However, integrating a dedicated multicolumn section directly into the theme would simplify the process for users and ensure a seamless and consistent design experience.

### **Additional context**
A multicolumn section adds a layer of sophistication and flexibility to the theme, accommodating diverse content presentation needs. With the prevalence of multicolumn layouts in modern web design, this feature would align the Shopify skeleton theme with current design trends, offering users more creative control over their storefronts.

![Sample Layout](https://github.com/dear-digital/shopify-theme-skeleton/assets/70633140/9654db01-9aac-40aa-aa00-c2e7283ad204)

[Reference Dawn](https://github.com/Shopify/dawn)

**Comment by mihir-bombay-studio** [comment]
Adding scope - correct tailwind integration
points - 3 -> 5
