### ISSUE TITLE
Add Multirow Section

### ISSUE THREAD

**Issue by kmalap05** [dear-digital/shopify-theme-skeleton#61]
**Is your feature request related to a problem? Please describe.**
I've identified a need for a Multirow section to enhance the layout customization options for users. Currently, the theme lacks support for creating multirow sections, limiting the ability to design complex and visually appealing layouts.

**Describe the solution you'd like**
I propose the addition of a Multirow section feature to the theme. This feature would allow users to create multirow layouts within a section, providing greater flexibility in designing diverse and dynamic content. The goal is to enable users to define multiple rows within a single section, each accommodating distinct content elements.

**Describe alternatives you've considered**
In considering this feature, alternative solutions such as utilizing existing sections or blocks for layout design were explored. However, a dedicated Multirow section would streamline the process and provide a more intuitive user experience for creating intricate layouts.

**Additional context**
Attached are wireframes or design mockups showcasing scenarios where the Multirow section would be beneficial. This feature request aims to address a gap in the current layout customization options and offers an opportunity to elevate the theme's usability for a diverse range of users.

![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/83391228/7c40fe68-a37d-473e-b51b-2a614b827139)

**Comment by mihir-bombay-studio** [comment]
Sections can already be seen as rows and we can keep adding sections to form a stack which fulfils this requirements. There is however a scope use blocks to add elements as rows inside some multi column sections to create multi column-multi row sections.

**Comment by kmalap05** [comment]
Ok
