### ISSUE TITLE
Add email sign up section

### ISSUE THREAD

**Issue by Mri1662** [dear-digital/shopify-theme-skeleton#63]
*Is your feature request related to a problem? Please describe.*
There might be various reasons to incorporate an email sign-up section, such as enhancing user engagement, building a subscriber base, or disseminating newsletters or updates to a broader audience.

*Describe the solution you'd like*
The feature request would entail the addition of an email sign-up section, typically found on websites or platforms. This section would enable users to input their email addresses voluntarily to subscribe to newsletters, receive updates, or access exclusive content.

*Describe alternatives you've considered*
Several alternatives might exist depending on the specific needs and context. These could include using third-party newsletter services like Mailchimp, integrating social media sign-ups, or employing pop-ups to prompt users to subscribe.

*Additional context*
Reference -->[dawn theme ]( https://github.com/Shopify/dawn/blob/main/sections/email-signup-banner.liquid)
![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/103936103/1cef08fe-74dc-47ad-ac7a-f40875047a4b)

**Comment by mihir-bombay-studio** [comment]
we already have an existing ticket for newsletter section #46
