### ISSUE TITLE
Errors while running Shopify theme check

### ISSUE THREAD

**Issue by abhishekjani08** [dear-digital/shopify-theme-skeleton#65]
**Describe the bug**
We can find many errors while we run `shopify theme check` command in our terminal or we can see them in the github actions as well.

**To Reproduce**
1. Go to Terminal of Vscode
2. Type command `shopify theme check` or else visit the Github Actions of our repository.
3. Errors are listed there.

**Screenshots**
In github actions we can see the annotations present:

![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/88500027/e923ad8c-5c9c-44f0-bdea-cdb14b73de50)

There are 30 notices and 6 warning which we can solve right now!
Files needed to be changed:

1. sections/image_banner.liquid
Errors present in this file are like:
- [SpaceInsideBraces] Space missing after ':'
- [SchemaJsonFormat] JSON formatting could be improved

2. sections/map.liquid
[SchemaJsonFormat] JSON formatting could be improved

3. sections/notification-bar.liquid 
[SchemaJsonFormat] JSON formatting could be improved

4. sections/carousel--two-rows.liquid
[DeprecatedFilter] Deprecated filter `img_url`, consider using `image_url`

5. sections/dev__background.liquid
SchemaJsonFormat: JSON formatting could be improved.
   
6. sections/dev__flex-box.liquid
SchemaJsonFormat: JSON formatting could be improved.
and other errors which we can view in github actions!

We can also solve the Schema JSON Formatting notice errors(there are 30 notices):
Out of those 30 notices, 6 notices are of these type:
![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/88500027/ceb8c2d3-b646-44bc-b6e3-7a89c0d5e3ad)
Formatting JSON schema is must to remove this error.

**For all the template errors:**
We'll need to add those required files as mentioned (From my perspective we should not add those files and validate the JSON right now, but we can solve the other errors which are mentioned above):
error: MissingRequiredTemplateFiles: 'templates/gift_card.liquid' or 'templates/gift_card.json' is missing.
error: MissingRequiredTemplateFiles: 'templates/customers/account.liquid' or 'templates/customers/account.json' is missing.
error: MissingRequiredTemplateFiles: 'templates/customers/activate_account.liquid' or 'templates/customers/activate_account.json' is missing.
error: MissingRequiredTemplateFiles: 'templates/customers/addresses.liquid' or 'templates/customers/addresses.json' is missing.
error: MissingRequiredTemplateFiles: 'templates/customers/login.liquid' or 'templates/customers/login.json' is missing.
error: MissingRequiredTemplateFiles: 'templates/customers/order.liquid' or 'templates/customers/order.json' is missing.
error: MissingRequiredTemplateFiles: 'templates/customers/register.liquid' or 'templates/customers/register.json' is missing.
![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/88500027/d0598697-a836-4502-958f-7decb0f71721)

**And after adding those files we will also have to Validate the JSON as mentioned:**
templates/cart.json: error: ValidJson: Invalid syntax in JSON.
templates/collection.json: error: ValidJson: Invalid syntax in JSON.
templates/page.json: error: ValidJson: Invalid syntax in JSON.
templates/product.json: error: ValidJson: Invalid syntax in JSON.
templates/search.json: error: ValidJson: Invalid syntax in JSON.
![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/88500027/56935edc-327b-49c4-8694-3322d5debdd0)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser : Chrome
 - Browser Version : Version 119.0.6045.160 (Official Build) (64-bit)
 - Current Shopify CLI version: 3.51.0

**Additional context**
The majority of the errors stem from JSON schema formatting issues across various liquid files. Deprecated usage of the img_url filter should be replaced with image_url. Required template files for gift cards and customer accounts are missing and need to be added. Once these files are added, the JSON within them needs to be validated to ensure proper syntax.

**Conclusion**
To maintain a high standard of quality for the Shopify theme, it's imperative to address all identified issues promptly. Rectifying the JSON schema formatting, updating deprecated filters, adding missing template files, and ensuring JSON syntax validity are essential steps towards a clean theme check pass. These fixes will enhance the theme's stability, compatibility, and overall performance, ultimately leading to a better end-user experience.

**Comment by mihir-bombay-studio** [comment]
Make sure to pull any new changes that are merged before making a PR so that any new code that is added into the main can also be error free.

**Comment by abhishekjani08** [comment]
I had some questions regarding this issue,

All the other errors are solved by me, just the errors of the template folder are remaining.

1. Should i create all these missing template files?
   When we run a theme check, these are the errors for the template files.

Ref image:
![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/88500027/11209be0-dd3f-40d5-a9cf-0a4a3418e158)


2. When created a JSON file in template folder, it cannot be empty.
    If it is empty, then the shopify theme check shows an error that the file cannot be empty.

Ref image:
![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/88500027/2ff3af98-2ef4-4a50-a3ed-5f28b8ebc185)

So i was thinking, to resolve this we can just keep a basic structure, we can start with something like this:
![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/88500027/1685346c-2cc1-4e6a-8fe9-b72f24f6db0f)
Just adding a basic structure JSON code will resolve this error.

Should i implement this things on files from template folder?
