### ISSUE TITLE
Add multi-column section to cards.liquid file

### ISSUE THREAD

**Issue by tanujbordikar** [dear-digital/shopify-theme-skeleton#66]
**Is your feature request related to a problem? Please describe.**
Currently, the cards section in the cards.liquid file only displays a single card per row. This limits the flexibility of the layout. To enhance the user experience, I propose adding a multi-column section with configurable settings.

**Describe the solution you'd like**
I suggest implementing a multi-column section in the `cards.liquid` file that allows users to configure the number of cards displayed per row. This would provide more flexibility in designing the layout.

**Describe alternatives you've considered**
One alternative is to leave the current implementation unchanged. However, this may limit the layout options for users who want to display multiple cards in a row.

**Additional context**
Current Issue:
![cardssection](https://github.com/dear-digital/shopify-theme-skeleton/assets/91179998/749e8462-6b58-478f-b2b3-a6504e9294d9)
Solution:
![multi-column](https://github.com/dear-digital/shopify-theme-skeleton/assets/91179998/84f516f2-c585-4e2b-bdb0-c91ead417e16)

**Comment by mihir-bombay-studio** [comment]
Similar section is under development #60 you make a new ticket if that ticket doesn't meet what you describe after it's completion.
