### ISSUE TITLE
Styling Testimonials Section in Row manner 

### ISSUE THREAD

**Issue by abhishekjani08** [dear-digital/shopify-theme-skeleton#68]
**Describe the bug**
Testimonials on the Shopify theme are currently displayed in a column layout. The preferred layout is to have them in a row, accommodating a maximum of three testimonials per row before starting a new one. Alternatively, consider implementing a slider for a large number of testimonials to enhance the user interface.

**To Reproduce**

1. Access the Shopify editor.
2. Navigate to and add a Testimonial Section.
3. Observe that testimonials are displayed in a column format rather than the desired row format.

**Expected Behavior**: 
The testimonials should be presented in rows, with proper styling applied to images to ensure a user-friendly interface. If the number of testimonials is high, a slider functionality should be introduced for better navigation.

**Screenshots**
![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/88500027/51a5007e-3b28-4840-bea1-d7042482b9ce)
Preferred layout is to have them in a row format with some text styling using BEM Methodology.

**Desktop (please complete the following information):**

1. OS: Windows
2. Browser : Chrome
3. Browser Version : Version 119.0.6045.160 (Official Build) (64-bit)
5. Current Shopify CLI version: 3.51.0

**Additional context**

**Comment by mihir-bombay-studio** [comment]
You can add a small incremental update to the Testimonials Section but make sure that we don't lose any existing features, for eg: the ability to display testimonials in a column format

**Comment by mihir-bombay-studio** [comment]
Issue ticket escalated from point 1 to point 2. PR execution aligned with guidelines and contributed to thematic enhancement. Noted for record and further action.
