### ISSUE TITLE
Add Custom Liquid with Section Padding

### ISSUE THREAD

**Issue by tanujbordikar** [dear-digital/shopify-theme-skeleton#71]
**Is your feature request related to a problem? Please describe.**
The Shopify theme is lacking the feature of customize configuration settings for adding liquid code [for eg. dawn/custom-liquid](https://github.com/Shopify/dawn/blob/main/sections/custom-liquid.liquid). And also lacks the ability to customize section padding (both top and bottom) in a straightforward manner. Users often require fine-grained control over the spacing within sections.

**Describe the solution you'd like**
I propose adding a feature to allow custom liquid with section padding. This would involve providing configuration settings for both top and bottom padding within individual sections. This feature would enhance the customization options available to users.

**Describe alternatives you've considered**
One alternative is to use external CSS for adjusting section padding. However, having an internal configuration option provides a more user-friendly and integrated solution.

**Additional context**
Reference image of dawn theme:
![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/91179998/73c91a3a-7ce7-40b5-9493-fd1816891d0d)

**Comment by mihir-bombay-studio** [comment]
You can add custom liquid section but don't add any custom padding as we can use css or tailwind to add any styling we want directly from the theme editor ref: [tailwind integrated file](https://github.com/dear-digital/shopify-theme-skeleton/blob/main/sections/demo__tailwind--simple-cta.liquid)
