### ISSUE TITLE
Add Slideshow feature

### ISSUE THREAD

**Issue by tanujbordikar** [dear-digital/shopify-theme-skeleton#72]
**Is your feature request related to a problem? Please describe.**
The current implementation lacks a slideshow section, limiting the ability to showcase dynamic content in a visually appealing manner. A slideshow section would enhance the user experience by allowing for the display of multiple images or content items.

**Describe the solution you'd like**
I propose adding a slideshow section with the following features:

- **JS Implementation:** Incorporate necessary JavaScript to make the slideshow interactive and dynamic.
- **CSS Styling:** Apply responsive styling using the BEM (Block, Element, Modifier) methodology to ensure the slideshow adapts to various screen sizes.
- **Configuration Settings:** Provide configurable settings for users to customize the slideshow behavior, such as transition effects, speed, and content.

**Describe alternatives you've considered**
One alternative is to use external libraries or plugins for slideshows but that may increase the cost and slow down the performance. However, having an internal slideshow section within the project allows for better integration and customization.

**Additional context**
Slideshow Configuration Settings:
![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/91179998/fddb7716-94b6-40c2-86d4-28cd756c102a)

Each Slide Configuration settings:
![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/91179998/54b1f09b-614c-4ac8-b6da-d478edc489d2)

I would appreciate any suggestions or considerations from you regarding the proposed slideshow section. This includes feedback on implementation details, best practices, or any existing documentations related to this feature.

**Comment by mihir-bombay-studio** [comment]
The scope of this ticket is too big at this point, are you sure you want to go for it? @tanujbordikar

**Comment by tanujbordikar** [comment]
> The scope of this ticket is too big at this point, are you sure you want to go for it? @tanujbordikar

I think I can work on this issue but if there, any issue arises I'll make sure to ask you for clearing it!
