### ISSUE TITLE
 Add custom liquid section 

### ISSUE THREAD

**Issue by Mri1662** [dear-digital/shopify-theme-skeleton#76]
**Is your feature request related to a problem? Please describe.**
I want to implement a custom liquid section similar to the one in the Dawn theme.  User cannot add own liquid like dawn theme.

**Describe the solution you'd like**
The solution involves adding a custom Liquid section to the theme to address the identified issue. This custom section would ideally provide the necessary functionality or content required, aligning with the design and structure.

**Describe alternatives you've considered**
Alternative solutions may have been explored, such as modifying existing Liquid elements or using built-in features of the platform.
The decision to add a custom Liquid section could be based on the limitations or inadequacies of the available alternatives.

**Additional context**
Reference -->[dawn theme](https://github.com/Shopify/dawn/blob/main/sections/custom-liquid.liquid)

<img width="217" alt="image" src="https://github.com/dear-digital/shopify-theme-skeleton/assets/103936103/67fd31d4-55f4-4a59-bbc4-640545299771">

**Comment by mihir-bombay-studio** [comment]
Ticket already exists #71
