### ISSUE TITLE
Schema Integration for [Section Name] = "collection-list"

### ISSUE THREAD

**Issue by Mri1662** [dear-digital/shopify-theme-skeleton#77]
**Is your feature request related to a problem? Please describe.**
The current implementation lacks schema integration for the “collection list” section, limiting its flexibility and data organization.

**Describe the solution you'd like**
Integrate a robust schema for the "collection list" section to enable structured data representation. This will enhance customization, compatibility with various data sources, and overall data organization.

**Describe alternatives you've considered**
Considered alternatives include exploring different data organization methods within the "collection list." However, schema integration is favored for its ability to provide a standardized and extensible solution.

**Additional context**
Reference  --> [dawn theme](https://github.com/Shopify/dawn/blob/main/sections/collection-list.liquid)

<img width="688" alt="image" src="https://github.com/dear-digital/shopify-theme-skeleton/assets/103936103/a24ed6ce-8dae-4a84-8a57-b031b482a50c">

**Comment by mihir-bombay-studio** [comment]
Make sure the new collection-list section follows tailwind section setup along with shopify best practices.
ref: [demo tailwind section](https://github.com/dear-digital/shopify-theme-skeleton/blob/main/sections/demo__tailwind--simple-cta.liquid)
