### ISSUE TITLE
Schema Integration for [Section Name] = "image-with-text-overlay"

### ISSUE THREAD

**Issue by Mri1662** [dear-digital/shopify-theme-skeleton#78]
**Is your feature request related to a problem? Please describe.**
The current schema lacks support for effective integration of the "image with text overlay" section, leading to limitations in presenting content seamlessly. This hinders the overall user experience and design flexibility.

**Describe the solution you'd like**
I propose the integration of a dedicated schema for the "image with text overlay" section. This schema should include fields for image upload, text input, and styling options for overlay text. Additionally, the schema should allow customization of overlay position, font styles, and background transparency to enhance creative control.

**Describe alternatives you've considered**
 Some users may use alternative sections or widgets to emulate the "image with text overlay" effect. However, this often results in a less intuitive and cohesive design.

**Additional context**
Reference Link --> [airthemeone](https://github.com/airthemeone/Shopify/blob/master/sections/image-with-text-overlay.liquid)

<img width="473" alt="image" src="https://github.com/dear-digital/shopify-theme-skeleton/assets/103936103/6fdada96-fc3f-466f-8504-fb7527bfa49f">

**Comment by tanujbordikar** [comment]
Hey @mihir-bombay-studio sir, can i work on this issue as no PRs are raised since week!
/attempt

**Comment by Mri1662** [comment]
But @mihir-bombay-studio  sir I am almost done this task

**Comment by mihir-bombay-studio** [comment]
@Mri1662 Would you still like to complete this task yourself or should I let someone else attempt it?
