### ISSUE TITLE
Schema Integration for [Section Name] = "video-text"

### ISSUE THREAD

**Issue by mihir-bombay-studio** [dear-digital/shopify-theme-skeleton#9]
Design can be found at website https://www.yummygums.com/.
Image of the section is pasted below.
![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/78968174/0f6ebab9-6747-4b27-a28f-2149e8129bad)

### Description
This issue involves integrating schema into the [Section Name] as per the design specifications of the Skeleton Shopify Theme. Add the file with the name `[section-name].liquid` to the `sections` folder if it does not exist already. This file will contain the schema for the [Section Name] section. The schema should be implemented according to the design specifications and allow for the necessary customization and input settings as identified in the design. The schema should also be tested and functional both on desktop and mobile views. Ensure that the code follows the project's coding standards and best practices. Any logical inconsistencies in the design should be addressed and standardized for end-user flexibility.

### Resources and Documentation
Before starting on this issue, please refer to our [Milestone 1: Schema Integration Documentation](https://github.com/dear-digital/shopify-theme-skeleton/blob/main/documentation/sections/README.md). This guide provides detailed steps and resources to assist you in this task.

### Acceptance Criteria
- [ ] The schema for [Section Name] is correctly implemented according to the design specifications.
- [ ] The schema allows for the necessary customization and input settings as identified in the design.
- [ ] Code follows the project's coding standards and best practices.
- [ ] Any logical inconsistencies in the design are addressed and standardized for end-user flexibility.

### How to Get Assigned
- If you're interested in working on this issue, comment `/attempt` below.
- You will be assigned based on your contribution level and previous work quality.
- Once assigned, you can start working on the issue and submit a pull request (PR) upon completion.

### Additional Notes
- Ensure to frequently communicate your progress and any challenges you face in this issue thread.
- If you have questions or need clarifications, feel free to ask in the comments or join our [Discord channel](https://discord.gg/axRUsACwPW) for a more in-depth discussion.

**Comment by kmalap05** [comment]
Can we initialize tailwindcss for this project or we should go with pure css?

**Comment by mihir-bombay-studio** [comment]
let's decide that later for now we only need the sections and schema structures for sections
