### ISSUE TITLE
Updating Newsletter Section

### ISSUE THREAD

**Issue by abhishekjani08** [dear-digital/shopify-theme-skeleton#90]
**Is your feature request related to a problem? Please describe.**
Updating and enhancing this shopify theme by adding a Newsletter section using **Tailwind CSS**.
Our current Shopify theme has a newsletter section but i think as we have introduced tailwind css into our theme we can integrate it with this section as well as it is more visually appealing to all the users and provides a good user experience.

**Describe the solution you'd like**
Introduce a new Newsletter section that is visually appealing and matches our branding, utilizing Tailwind CSS for styling. This section should be responsive and integrate seamlessly with our existing design.
Screenshot:
![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/88500027/dd6f46b0-ff8f-4d49-aa2c-f1d73367cc20)

**Describe alternatives you've considered**
The primary goal is to add the newsletter functionality in a way that aligns with the current UX of our theme.

**Additional context**
The Newsletter section should include:
- A headline prompting users to subscribe
- An input field for the email address
- A submit button with clear call-to-action
- Compliance with accessibility and GDPR guidelines

**Comment by mihir-bombay-studio** [comment]
@abhishekjani08 I've mistakenly added points twice here, I'll adjust them from the issue number #96 which also has the same amount of points
