### ISSUE TITLE
Notification Bar Redesign using Tailwind

### ISSUE THREAD

**Issue by anishdalvi** [dear-digital/shopify-theme-skeleton#91]
### **Is your feature request related to a problem? Please describe.**
Currently, our Shopify theme notification bar's design needs improvement for a better user experience.

### **Describe the solution you'd like**
I aim to address these challenges by designing a visually appealing notification bar using Tailwind CSS. Tailwind will allow for efficient and flexible styling.The notification will have this basic design and I will try to enhance it more if possible during development.

![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/70633140/7e728c08-7b28-4593-81cd-9524fd47fc3f)

### **Describe alternatives you've considered**
For the notification bar, alternatives include using other CSS frameworks or manual styling. However, Tailwind CSS is our choice so I will go with it.

### **Additional context**
By enhancing the notification bar design, I aim to create a more polished and error-free Shopify theme, ultimately improving the user experience for visitors to our store.

**Comment by anishdalvi** [comment]
Cool!

**Comment by mihir-bombay-studio** [comment]
Bumping points 2-> 3 for understanding and implementation of tailwind in #98
