### ISSUE TITLE
Enhance Header Section with Resizable Logo and Customizable Background

### ISSUE THREAD

**Issue by abhishekjani08** [dear-digital/shopify-theme-skeleton#96]
**Is your feature request related to a problem? Please describe.**
Currently, the header section's logo is not resizable, and the background color is statically set to gray, which limits branding customization for store owners.

**Describe the solution you'd like**

- Logo Resizing: Introduce a slider within the theme settings to allow users to resize the logo easily. 

- Background Color Picker: Implement a color picker option for the header background to provide more flexibility in matching the store's brand colors.

**Expected Behavior**
The logo should be adjustable with a range of predefined sizes for better visual compatibility across different devices.
Users should be able to choose any color for the header background, enhancing the store's visual appeal and brand consistency.

**Screenshots:**

- On default, it will show you the shop name as logo:
![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/88500027/183e8c53-f0a3-41e9-9c5a-d79a6d165924)

- Logo resized to a smaller dimension: 
![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/88500027/d4a0dd8b-4b35-4b5e-8afe-b1be81370618)

- Logo resized to a larger dimension: 
![image](https://github.com/dear-digital/shopify-theme-skeleton/assets/88500027/8a0308fa-ca09-4486-9d30-3d8ed26612ee)

Also, the color picker to be added as to choose a bg color for the header.
🚀All other features present remains the same!

**Comment by mihir-bombay-studio** [comment]
Removed points to adjust double point mistake in issue #90
